name: saas_lakehouse
version: 1.0
config-version: 2

profile: saas_lakehouse

model-paths: ["models"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]

models:
  saas_lakehouse:
    staging:
      materialized: view
    intermediate:
      materialized: view
    core:
      materialized: table
    marts:
      materialized: table